services:
  sns-upload-server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      # STRAPI Server Config
      STRAPI_HOST: ${STRAPI_HOST}
      STRAPI_PORT: ${STRAPI_PORT}
      STRAPI_BASEURL: ${STRAPI_BASEURL}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT} 
      APP_KEYS: ${APP_KEYS}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REFRESH_TOKEN_EXPIRES: ${REFRESH_TOKEN_EXPIRES}
      JWT_SECRET_EXPIRES: ${JWT_SECRET_EXPIRES}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # GCP CONFIG
      GOOGLE_STORAGE_BUCKETNAME: ${GOOGLE_STORAGE_BUCKETNAME}
      GCS_SERVICE_ACCOUNT: ${GCS_SERVICE_ACCOUNT}
      # SENDGRID CONFIG
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_DEFAULT_FROM: ${SENDGRID_DEFAULT_FROM}
      SENDGRID_DEFAULT_REPLYTO: ${SENDGRID_DEFAULT_REPLYTO}
      # MEILI SEARCH CONFIG
      MEILI_SEARCH_BASEURL: ${MEILI_SEARCH_BASEURL}
      MEILI_SEARCH_APIKEY: ${MEILI_SEARCH_APIKEY}
      # PAYMONGO CONFIG
      PAYMONGO_SECRET_KEY: ${PAYMONGO_SECRET_KEY}
    ports:
      - 1338:1338
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${STRAPI_PORT}/"]
      interval: 5s
      timeout: 5s
      retries: 3